version: '3.9'

volumes:
  review_vol:
  movie_vol:
 

networks:
  micronet:
    driver: bridge

services:

  postgres_review_db:
    image: postgres:14.1
    restart: always
    networks:
      - micronet
    volumes:
      - review_vol:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=Pg@123
      - POSTGRES_DB=pguser

  mongo_movies_db:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017
    networks:
      - micronet
    volumes:
      - movie_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  movies:
    image: marc2play/movie:v1
    restart: always
    networks:
      - micronet
    ports:
      - 8181:8181
    depends_on:
      - mongo_movies_db
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@mongo_movies_db:27017/admin

  review:
    image: marc2play/review:v1
    restart: always
    networks:
      - micronet
    ports:
      - 8080:80
    depends_on:
      - postgres_review_db
    environment:
      ConnectionStrings__MyConnection: Host=postgres_review_db;Database=pguser;Username=pguser;Password=Pg@123;

  rotten:
    image: marc2play/rotten:v1
    restart: always
    networks:
      - micronet
    ports:
      - 5000:5000
    depends_on:
      - review
      - movies
    volumes:
      - movie_vol:/data/db
    environment:
      MOVIE_SERVICE_URI: http://movies:8181
      REVIEW_SERVICE_URI: http://review:80
